package com.example.shopmanager.service.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.shopmanager.service.db.bean.BookInfo;
import com.example.shopmanager.service.db.bean.ShoppingCart;
import com.example.shopmanager.service.db.bean.UserInfo;
import com.example.shopmanager.service.db.bean.TrendsInfo;

import com.example.shopmanager.service.db.dao.BookInfoDao;
import com.example.shopmanager.service.db.dao.ShoppingCartDao;
import com.example.shopmanager.service.db.dao.UserInfoDao;
import com.example.shopmanager.service.db.dao.TrendsInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookInfoDaoConfig;
    private final DaoConfig shoppingCartDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig trendsInfoDaoConfig;

    private final BookInfoDao bookInfoDao;
    private final ShoppingCartDao shoppingCartDao;
    private final UserInfoDao userInfoDao;
    private final TrendsInfoDao trendsInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookInfoDaoConfig = daoConfigMap.get(BookInfoDao.class).clone();
        bookInfoDaoConfig.initIdentityScope(type);

        shoppingCartDaoConfig = daoConfigMap.get(ShoppingCartDao.class).clone();
        shoppingCartDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        trendsInfoDaoConfig = daoConfigMap.get(TrendsInfoDao.class).clone();
        trendsInfoDaoConfig.initIdentityScope(type);

        bookInfoDao = new BookInfoDao(bookInfoDaoConfig, this);
        shoppingCartDao = new ShoppingCartDao(shoppingCartDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        trendsInfoDao = new TrendsInfoDao(trendsInfoDaoConfig, this);

        registerDao(BookInfo.class, bookInfoDao);
        registerDao(ShoppingCart.class, shoppingCartDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(TrendsInfo.class, trendsInfoDao);
    }
    
    public void clear() {
        bookInfoDaoConfig.clearIdentityScope();
        shoppingCartDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
        trendsInfoDaoConfig.clearIdentityScope();
    }

    public BookInfoDao getBookInfoDao() {
        return bookInfoDao;
    }

    public ShoppingCartDao getShoppingCartDao() {
        return shoppingCartDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public TrendsInfoDao getTrendsInfoDao() {
        return trendsInfoDao;
    }

}
